const { renderEmailLayout } = require('./layout');
const { escapeHtml, nl2br } = require('./escape');

function renderTranscriptReport({ meetingTitle, label, orgName, summaryExcerpt }) {
  const title = meetingTitle || 'Meeting';
  const reportLabel = label || 'Meeting report';
  const subject = `${reportLabel}: ${title} — Lalia`;
  const text = [
    `Attached is the ${reportLabel.toLowerCase()} for "${title}"${orgName ? ` (${orgName})` : ''}, generated by Lalia.`,
    '',
    summaryExcerpt ? `Preview:\n${summaryExcerpt.slice(0, 1200)}` : '',
    '',
    'The full report is attached as a PDF.',
  ]
    .filter(Boolean)
    .join('\n');

  const detailRows = [
    { label: 'Meeting', value: title },
    { label: 'Report', value: reportLabel },
  ];
  if (orgName) detailRows.push({ label: 'Workspace', value: orgName });

  const html = renderEmailLayout({
    preheader: `${reportLabel} for ${title} is attached as a PDF.`,
    title: reportLabel,
    introHtml: `<p style="margin:0;">Here's the <strong>${escapeHtml(reportLabel.toLowerCase())}</strong> for <strong>${escapeHtml(title)}</strong>${orgName ? ` from ${escapeHtml(orgName)}` : ''}. The full report is attached as a PDF.</p>`,
    detailRows,
    secondaryHtml: summaryExcerpt
      ? `<div style="margin-top:8px;padding:16px;border-radius:12px;background:#f8fafc;border:1px solid #e2e8f0;"><p style="margin:0 0 8px;font-size:12px;font-weight:600;letter-spacing:0.04em;text-transform:uppercase;color:#64748b;">Preview</p><div style="font-size:14px;line-height:1.65;color:#334155;">${nl2br(summaryExcerpt.slice(0, 1200))}</div></div>`
      : '',
    footerNote: 'This report was shared from a Lalia meeting workspace.',
  });

  return { subject, text, html };
}

module.exports = { renderTranscriptReport };
