const CONTROL_LABELS = {
  en: {
    microphone: 'Microphone',
    camera: 'Camera',
    shareScreen: 'Share screen',
    stopSharing: 'Stop sharing',
    chat: 'Chat',
    captions: 'Captions',
    people: 'People',
    share: 'Share',
    leave: 'Leave',
    startAudio: 'Click to enable audio',
    you: 'You',
    messagePlaceholder: 'Message…',
    sendMessage: 'Send message',
    noMessages: 'No messages yet. Say hi.',
    translating: 'Translating…',
    showMyCaptions: 'Show my captions',
    showCaptions: 'Show captions',
    yourLanguage: 'Your language',
    roomBroadcast: 'Room broadcast',
    captionsOff: 'Captions off',
    transcriptionOnly: 'Transcription only',
    transcriptionTranslation: 'Transcription + Translation',
  },
  es: {
    microphone: 'Micrófono',
    camera: 'Cámara',
    shareScreen: 'Compartir pantalla',
    stopSharing: 'Dejar de compartir',
    chat: 'Chat',
    captions: 'Subtítulos',
    people: 'Personas',
    share: 'Compartir',
    leave: 'Salir',
    startAudio: 'Haz clic para activar el audio',
    you: 'Tú',
    messagePlaceholder: 'Mensaje…',
    sendMessage: 'Enviar mensaje',
    noMessages: 'Aún no hay mensajes. Saluda.',
    translating: 'Traduciendo…',
    showMyCaptions: 'Mostrar mis subtítulos',
    showCaptions: 'Mostrar subtítulos',
    yourLanguage: 'Tu idioma',
    roomBroadcast: 'Transmisión de la sala',
    captionsOff: 'Subtítulos desactivados',
    transcriptionOnly: 'Solo transcripción',
    transcriptionTranslation: 'Transcripción + traducción',
  },
  fr: {
    microphone: 'Microphone',
    camera: 'Caméra',
    shareScreen: "Partager l'écran",
    stopSharing: 'Arrêter le partage',
    chat: 'Chat',
    captions: 'Sous-titres',
    people: 'Personnes',
    share: 'Partager',
    leave: 'Quitter',
    startAudio: "Cliquez pour activer l'audio",
    you: 'Vous',
    messagePlaceholder: 'Message…',
    sendMessage: 'Envoyer le message',
    noMessages: "Aucun message pour l'instant. Dites bonjour.",
    translating: 'Traduction…',
    showMyCaptions: 'Afficher mes sous-titres',
    showCaptions: 'Afficher les sous-titres',
    yourLanguage: 'Votre langue',
    roomBroadcast: 'Diffusion de la salle',
    captionsOff: 'Sous-titres désactivés',
    transcriptionOnly: 'Transcription uniquement',
    transcriptionTranslation: 'Transcription + traduction',
  },
  de: {
    microphone: 'Mikrofon',
    camera: 'Kamera',
    shareScreen: 'Bildschirm teilen',
    stopSharing: 'Teilen beenden',
    chat: 'Chat',
    captions: 'Untertitel',
    people: 'Personen',
    share: 'Teilen',
    leave: 'Verlassen',
    startAudio: 'Klicken, um Audio zu aktivieren',
    you: 'Sie',
    messagePlaceholder: 'Nachricht…',
    sendMessage: 'Nachricht senden',
    noMessages: 'Noch keine Nachrichten. Sagen Sie Hallo.',
    translating: 'Übersetzen…',
    showMyCaptions: 'Meine Untertitel anzeigen',
    showCaptions: 'Untertitel anzeigen',
    yourLanguage: 'Ihre Sprache',
    roomBroadcast: 'Raumübertragung',
    captionsOff: 'Untertitel aus',
    transcriptionOnly: 'Nur Transkription',
    transcriptionTranslation: 'Transkription + Übersetzung',
  },
  pt: {
    microphone: 'Microfone',
    camera: 'Câmera',
    shareScreen: 'Compartilhar tela',
    stopSharing: 'Parar compartilhamento',
    chat: 'Chat',
    captions: 'Legendas',
    people: 'Pessoas',
    share: 'Compartilhar',
    leave: 'Sair',
    startAudio: 'Clique para ativar o áudio',
    you: 'Você',
    messagePlaceholder: 'Mensagem…',
    sendMessage: 'Enviar mensagem',
    noMessages: 'Ainda não há mensagens. Diga oi.',
    translating: 'Traduzindo…',
    showMyCaptions: 'Mostrar minhas legendas',
    showCaptions: 'Mostrar legendas',
    yourLanguage: 'Seu idioma',
    roomBroadcast: 'Transmissão da sala',
    captionsOff: 'Legendas desativadas',
    transcriptionOnly: 'Somente transcrição',
    transcriptionTranslation: 'Transcrição + tradução',
  },
  ja: {
    microphone: 'マイク',
    camera: 'カメラ',
    shareScreen: '画面を共有',
    stopSharing: '共有を停止',
    chat: 'チャット',
    captions: '字幕',
    people: '参加者',
    share: '共有',
    leave: '退出',
    startAudio: 'クリックして音声を有効にする',
    you: '自分',
    messagePlaceholder: 'メッセージ…',
    sendMessage: 'メッセージを送信',
    noMessages: 'まだメッセージはありません。挨拶してみましょう。',
    translating: '翻訳中…',
    showMyCaptions: '自分の字幕を表示',
    showCaptions: '字幕を表示',
    yourLanguage: '自分の言語',
    roomBroadcast: 'ルーム配信',
    captionsOff: '字幕オフ',
    transcriptionOnly: '文字起こしのみ',
    transcriptionTranslation: '文字起こし + 翻訳',
  },
  'zh-CN': {
    microphone: '麦克风',
    camera: '摄像头',
    shareScreen: '共享屏幕',
    stopSharing: '停止共享',
    chat: '聊天',
    captions: '字幕',
    people: '成员',
    share: '分享',
    leave: '离开',
    startAudio: '点击启用音频',
    you: '你',
    messagePlaceholder: '消息…',
    sendMessage: '发送消息',
    noMessages: '还没有消息。打个招呼吧。',
    translating: '正在翻译…',
    showMyCaptions: '显示我的字幕',
    showCaptions: '显示字幕',
    yourLanguage: '你的语言',
    roomBroadcast: '房间广播',
    captionsOff: '关闭字幕',
    transcriptionOnly: '仅转录',
    transcriptionTranslation: '转录 + 翻译',
  },
};

export const ROOM_CONTROL_LABEL_KEYS = Object.freeze(Object.keys(CONTROL_LABELS.en));

export function controlLabel(language, key) {
  const raw = String(language || 'en');
  const exact = raw === 'zh-cn' ? 'zh-CN' : raw;
  const base = exact.split('-')[0].toLowerCase();
  return CONTROL_LABELS[exact]?.[key] || CONTROL_LABELS[base]?.[key] || CONTROL_LABELS.en[key] || key;
}
